In [4]:
import pandas as pd
df = pd.read_csv("anage_animalia.csv")
df

,HAGRID,Kingdom,Phylum,Class,Order,Family,Genus,Species,Common name,Female maturity (days),...,Source,Specimen origin,Sample size,Data quality,IMR (per yr),MRDT (yrs),Metabolic rate (W),Body mass (g),Temperature (K),References
0,32,Animalia,Chordata,Amphibia,Anura,Ascaphidae,Ascaphus,truei,Coastal tailed frog,NaN,...,525,wild,medium,acceptable,NaN,NaN,NaN,NaN,NaN,"525,749"
1,33,Animalia,Chordata,Amphibia,Anura,Bombinatoridae,Bombina,bombina,Firebelly toad,1095.0,...,485,captivity,medium,acceptable,NaN,NaN,NaN,NaN,NaN,"485,525,749"
2,34,Animalia,Chordata,Amphibia,Anura,Bombinatoridae,Bombina,orientalis,Oriental firebelly toad,NaN,...,451,captivity,large,acceptable,NaN,NaN,NaN,NaN,NaN,"451,525,749"
3,35,Animalia,Chordata,Amphibia,Anura,Bombinatoridae,Bombina,variegata,Yellow-bellied toad,NaN,...,NaN,captivity,medium,acceptable,NaN,NaN,NaN,NaN,NaN,"24,525,749"
4,36,Animalia,Chordata,Amphibia,Anura,Bufonidae,Anaxyrus,americanus,American toad,910.0,...,525,captivity,medium,acceptable,NaN,NaN,0.00829,21.6,288.0,"37,268,426,525,749"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4508,4595,Animalia,Chordata,Teleostei,Zeiformes,Oreosomatidae,Allocyttus,niger,Black oreo,9855.0,...,454,wild,medium,acceptable,NaN,NaN,NaN,NaN,NaN,454
4509,4596,Animalia,Chordata,Teleostei,Zeiformes,Oreosomatidae,Allocyttus,verrucosus,Warty oreo,NaN,...,22,wild,medium,acceptable,NaN,NaN,NaN,NaN,NaN,"22,454"
4510,4597,Animalia,Chordata,Teleostei,Zeiformes,Oreosomatidae,Neocyttus,rhomboidalis,Spiky oreo,NaN,...,454,wild,medium,acceptable,NaN,NaN,NaN,NaN,NaN,454
4511,4598,Animalia,Chordata,Teleostei,Zeiformes,Oreosomatidae,Pseudocyttus,maculatus,Smooth oreo,11315.0,...,454,wild,medium,acceptable,NaN,NaN,NaN,NaN,NaN,454
4512,4599,Animalia,Chordata,Teleostei,Zeiformes,Zeidae,Zeus,faber,European john dory,1277.0,...,454,wild,medium,acceptable,NaN,NaN,NaN,NaN,NaN,454

In [7]:
df.columns

Index(['HAGRID', 'Kingdom', 'Phylum', 'Class', 'Order', 'Family', 'Genus',
       'Species', 'Common name', 'Female maturity (days)',
       'Male maturity (days)', 'Gestation/Incubation (days)', 'Weaning (days)',
       'Litter/Clutch size', 'Litters/Clutches per year',
       'Inter-litter/Interbirth interval', 'Birth weight (g)',
       'Weaning weight (g)', 'Adult weight (g)', 'Growth rate (1/days)',
       'Maximum longevity (yrs)', 'Source', 'Specimen origin', 'Sample size',
       'Data quality', 'IMR (per yr)', 'MRDT (yrs)', 'Metabolic rate (W)',
       'Body mass (g)', 'Temperature (K)', 'References'],
      dtype='str')

In [36]:
df.isna().sum()

HAGRID                                 0
Kingdom                                0
Phylum                                 0
Class                                  0
Order                                  0
Family                                 0
Genus                                  0
Species                                0
Common name                            0
Female maturity (days)              2054
Male maturity (days)                2633
Gestation/Incubation (days)         2680
Weaning (days)                      3745
Litter/Clutch size                  2422
Litters/Clutches per year           3209
Inter-litter/Interbirth interval    3748
Birth weight (g)                    3283
Weaning weight (g)                  4129
Adult weight (g)                     872
Growth rate (1/days)                3954
Maximum longevity (yrs)              488
Source                               554
Specimen origin                        0
Sample size                            0
Data quality                           0
IMR (per yr)                        4473
MRDT (yrs)                          4477
Metabolic rate (W)                  3886
Body mass (g)                       3886
Temperature (K)                     4019
References                             1
dtype: int64

In [34]:
df[["Data quality", "Specimen origin", "Sample size"]]

     Data quality Specimen origin Sample size
0      acceptable            wild      medium
1      acceptable       captivity      medium
2      acceptable       captivity       large
3      acceptable       captivity      medium
4      acceptable       captivity      medium
...           ...             ...         ...
4508   acceptable            wild      medium
4509   acceptable            wild      medium
4510   acceptable            wild      medium
4511   acceptable            wild      medium
4512   acceptable            wild      medium

[4513 rows x 3 columns]

In [49]:
df["Data quality"].value_counts()

Data quality
acceptable      3816
low              488
high             108
questionable     101
Name: count, dtype: int64

In [50]:
df["Specimen origin"].value_counts()

Specimen origin
wild         2008
captivity    1902
unknown       603
Name: count, dtype: int64

In [52]:
df["Sample size"].value_counts()

Sample size
medium    2408
small     1404
large      382
tiny       318
huge         1
Name: count, dtype: int64

1.Al analizar la base de datos nos damos cuenta que existen demasiados datos inexistentes e varias columnas, en algunas estos datos inexistentes superan el 50% de la muestra, lo que sugiere que si analzamos estas columnas no sera un muy buen analisis.